### ISSUE TITLE
使用element-ui报错

### ISSUE THREAD

**Issue by Qinhank** [aoi-umi/webpack-dynamic-import-cdn-plugin#1]
应该是名称的问题
报：Uncaught ReferenceError: element is not defined

**Comment by aoi-umi** [comment]
> 应该是名称的问题
> 报：Uncaught ReferenceError: element is not defined

配置咋写的？

**Comment by aoi-umi** [comment]
我试了下，elementui的定义是typeof define&&define.amd?define("ELEMENT",["vue"],t)
然后这样写
```js
'element-ui': {
    moduleName: 'ELEMENT',
    url: 'https://unpkg.com/element-ui@2.13.2/lib/index.js'
}
```
是可以的

**Comment by aoi-umi** [comment]
@Qinhank 没什么问题就关掉咯

**Comment by Qinhank** [comment]
好的，谢谢。
后面我也发现它全局是ELEMENT，搞得我在那猜来猜去。
