### ISSUE TITLE
最近有个设想，就是在不同的微服务之间，如何共享模块，动态的使用CDN导入

### ISSUE THREAD

**Issue by lzxb** [aoi-umi/webpack-dynamic-import-cdn-plugin#2]
看了楼主的这个，似乎比较能满足我的需求。

**Comment by lzxb** [comment]
不知道楼主有没有兴趣，拿这个demo搞一个插件，支持不同微服务之间，可以异步的导入CDN文件
https://github.com/fmfe/vue-genesis-micro

**Comment by aoi-umi** [comment]
有点复杂，细说下？

**Comment by lzxb** [comment]
在SSR微服务场景下，一个页面，由多个项目打包组合而成，不同的项目之间，都会使用到一些相同的依赖，比如常见的echarts、pixi.js等等。这个都会造成重复的打包，除非把这些包，全部都放到所有服务之间进行加载，但是很多库，一开始的时候，并不会立马就会使用，在这个时候，就需要做到需要的时候，再去动态的插入CSS和JS文件，加载对应的CDN文件。

**Comment by lzxb** [comment]
就以www.followme.com首页来讲，这个页面由四个服务聚合而成，导致有很多相同的依赖，都被打包进去了，造成初始化的时候，特别大

![image](https://user-images.githubusercontent.com/8424643/105955737-b198ef80-60b1-11eb-9e0c-2ea1596bc75f.png)

**Comment by lzxb** [comment]
![image](https://user-images.githubusercontent.com/8424643/105957811-b7dc9b00-60b4-11eb-9b2d-e992f874b938.png)
![image](https://user-images.githubusercontent.com/8424643/105957828-be6b1280-60b4-11eb-84c7-a556956258b7.png)

哈哈，看了一下。这个和我想的一模一样。

**Comment by aoi-umi** [comment]
我看构建的部分也是用webpack，你试试把这个组件加进去

**Comment by lzxb** [comment]
我试过了，报错了。我自己搞的话，估计要花点时间了，最近太忙了。

**Comment by aoi-umi** [comment]
你可以弄个分支给我看看你咋搞的

**Comment by lzxb** [comment]
![image](https://user-images.githubusercontent.com/8424643/106221559-ce036c00-6218-11eb-961c-32a4d019231f.png)

第一个报错就是这个。

**Comment by lzxb** [comment]
你看下这个分支：
https://github.com/fmfe/vue-genesis-micro/tree/feat-dynamic-import-cdn

**Comment by lzxb** [comment]
![image](https://user-images.githubusercontent.com/8424643/106222064-bb3d6700-6219-11eb-91f2-9ca62f59381a.png)

到时候还需要生成类似这样的，这样才能在SSR服务初始化的时候加载。

**Comment by lzxb** [comment]
这里会分为初始化的时候加载，以及分割路由后，按需加载的文件。

**Comment by aoi-umi** [comment]
html-webpack-plugin-before-html-generation是来自插件HtmlWebpackPlugin的
因为我直接用vue-cli的，不需要自己添加，所以不清楚你这个项目怎么加进去

**Comment by lzxb** [comment]
我的项目不需要使用这个插件 `html-webpack-plugin-before-html-generation`，所以想问问大佬有没有办法兼容一下。

**Comment by aoi-umi** [comment]
```js
compilation.plugin('html-webpack-plugin-before-html-generation', function (htmlPluginData) {
                function unshiftCdn(cdn, assets) {
                    let list = [];
                    for (let key in cdn) {
                        list.push(cdn[key]);
                    }
                    if (list.length)
                        assets.unshift(...list);
                }
                unshiftCdn(globalCdn.js, htmlPluginData.assets.js);
                unshiftCdn(globalCdn.css, htmlPluginData.assets.css);
                return htmlPluginData;
            });
```
这个是我原本的写法，这里主要就是把cdn的地址放到htmlPluginData.assets里，如果不用这个的话就要看你在哪里处理这一块了

**Comment by lzxb** [comment]
还需要来研究一下。

**Comment by fengsx** [comment]
哈哈，不谋而合。我把这个库修了些 bug，完善了 ts，做成了 [umi 的一个插件](https://github.com/fengsx/umi-plugin-dynamic-import-from-cdn) 解决这个问题。。

**Comment by lzxb** [comment]
> 哈哈，不谋而合。我把这个库修了些 bug，完善了 ts，做成了 [umi 的一个插件](https://github.com/fengsx/umi-plugin-dynamic-import-from-cdn) 解决这个问题。。

大佬来研究一下，给Genesis也搞个插件。

**Comment by aoi-umi** [comment]
我觉得搞不了，加了个前缀( ﾟ∀。)
![image](https://user-images.githubusercontent.com/17681077/106996315-b5b4c380-67bb-11eb-85c6-bb7fed0729d5.png)

![image](https://user-images.githubusercontent.com/17681077/106996094-37f0b800-67bb-11eb-83a0-a3e3ebd8fd2c.png)

**Comment by aoi-umi** [comment]
render拼了个前缀上去
![image](https://user-images.githubusercontent.com/17681077/106998936-4392ad80-67c0-11eb-9708-8612e0dae03a.png)

**Comment by lzxb** [comment]
这个你可以写入到另外一个json的文件。然后我去读取这个json文件。写入到html中

**Comment by lzxb** [comment]
可以不破坏vue插件原始json

**Comment by lzxb** [comment]
或者我写个正则，替换掉

**Comment by aoi-umi** [comment]
我不清楚这个插件怎么调用的，但最简单的方法就是修改render
是这里的，应该判断http(s)://开头的不用加前缀
https://github.com/fmfe/genesis/blob/2d381a355ac3aa3e0cda1b10a3ff8208456ef857/packages/genesis-core/src/renderer.ts#L77

**Comment by lzxb** [comment]
https://github.com/fmfe/vue-genesis-micro/commit/ca199e8b71ee5f8764e5099a7b8f01316687952d

你看下我的这个提交

**Comment by lzxb** [comment]
可能正则写得不对，你可以修改试试。

**Comment by lzxb** [comment]
感觉成功只有一步之遥了。

**Comment by aoi-umi** [comment]
这里也要改，我改成自己渲染就行了
data.script =
                `<script>window["__webpack_public_path_${ssr.name}__"] = "${baseUrl}";</script>` +
                data.script +
                resource.filter(ele => ele.extension === 'js')
                    .map(ele => `<script src="${ele.file}" defer></script>`).join('');
            // vueCtx.renderScripts();

**Comment by lzxb** [comment]
你试试，看看能不能搞出一个可以跑通的demo

**Comment by lzxb** [comment]
你有提交代码吗？我可以拉下来看看问题。

**Comment by aoi-umi** [comment]
我的插件还没更新到npm

**Comment by aoi-umi** [comment]
> 你有提交代码吗？我可以拉下来看看问题。

没开权限

**Comment by lzxb** [comment]
我现在在升级webpack5，现在终于有时间了。我打算把你的插件，直接纳入到我的标准库中

**Comment by aoi-umi** [comment]
> 我现在在升级webpack5，现在终于有时间了。我打算把你的插件，直接纳入到我的标准库中

之前说的问题都可以了吗
